### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by ahmerique** [kmatheussen/common-ladspa-plugins#1]
Hey!

I don't quite get how to install your plugins on a Windows 64 bits.
I don't need MXE or OSXcross right? As they are for Linux and OS X.

But when I launch ./build_all.sh from MSYS2-Mingw64 I only get a build for Linux64.
Many thanks!

Edit: My bad, my gcc compiler was not named "x86_64-w64-mingw32.shared-gcc" but  ""x86_64-w64-mingw32-gcc". I just had to change it on the build_mingw64.sh

**Comment by kmatheussen** [comment]
Hi, you probably need to tweak the scripts a little, as you found out. Also, if you only need the ladspa plugins, not a way to compile them. just download a demo version of the radium music editor. The plugins are included somewhere in those zip files (I would guess under bin/ladspa).

**Comment by kmatheussen** [comment]
Oh, and rather than running the build_ming64.sh script directly, you should edit build_all.sh and run that one instead.

**Comment by ahmerique** [comment]
Thanks! I got them.
Well I'm trying to use it with gstreamer just like in Linux but it does not recognize the plugins for the moment. I don't know if I am missing something.
